[font]
normal = { family = "Myrica M", style = "Book" }
size = 16.0

[window]
decorations = "Transparent"
opacity = 0.65
blur = true
padding = { x = 10, y = 58 }
dynamic_padding = true
title = ""

[[keyboard.bindings]]
key = "Return"
mods = "Command"
action = "ToggleFullscreen"
