[font]
normal = { family = "Myrica M", style = "Book" }
size = 16.0

[window]
opacity = 0.75
blur = true
padding = { x = 10, y = 10 }
dynamic_padding = true
title = ""

[[keyboard.bindings]]
key = "Return"
mods = "Command"
action = "ToggleFullscreen"
